Update deploy-api.yml

diff --git a/.github/workflows/deploy-api.yml b/.github/workflows/deploy-api.yml
--- a/.github/workflows/deploy-api.yml
+++ b/.github/workflows/deploy-api.yml
@@ -51,9 +51,9 @@ jobs:
             docker build -t bn-api . || { echo "Docker build failed"; exit 1; }
       
             echo "== Stopping and removing old container (if any) =="
-            docker stop bn-api || true
-            docker rm bn-api || true
+            sudo docker stop bn-api || true
+            sudo docker rm bn-api || true
       
             echo "== Running new container =="
-            docker run -d -p 5001:5001 --name bn-api --env-file .env bn-api || { echo "Docker run failed"; exit 1
+            sudo docker run -d -p 5001:5001 --name bn-api --env-file .env bn-api || { echo "Docker run failed"; exit 1
 
